#!/bin/bash
export CROSS_COMPILE=~/Desktop/Android/toolchains/aarch64-linux-android-4.9/bin/aarch64-linux-android-
make mrproper
export ARCH=arm64
make O=out TARGET_ARCH=arm64 l5460_defconfig
make O=out TARGET_ARCH=arm64 menuconfig
make O=out TARGET_ARCH=arm64 -j8
