#!/bin/bash
export CROSS_COMPILE=~/Desktop/Android/toolchains/aarch64-linux-android-4.9/bin/aarch64-linux-android-
export ARCH=arm64
make O=out TARGET_ARCH=arm64 oldconfig
make O=out TARGET_ARCH=arm64 menuconfig
make O=out TARGET_ARCH=arm64 -j8
